version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    groups:
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
